Users\Domain\Calendar:
  type: entity
  table: calendars

  id:
    uuid:
      type: string
      generator:
        strategy: NONE

  fields:
    semester:
      type: string
      nullable: false

  oneToOne:
    user:
      targetEntity: User
      mappedBy: calendar

  oneToMany:
    months:
      cascade: ["persist"]
      targetEntity: Month
      mappedBy: calendar
