Users\Domain\Month:
  type: entity
  table: months

  id:
    uuid:
      type: string
      generator:
        strategy: NONE

  fields:
    monthNumber:
      type: integer
      nullable: false
    workingHours:
      type: integer
      nullable: false

  manyToOne:
    calendar:
      targetEntity: Calendar
      inversedBy: months
      joinColumn:
        name: calendar_uuid
        referencedColumnName: uuid
