Users\Domain\Qualification:
  type: entity
  table: qualifications

  id:
    uuid:
      type: string
      generator:
        strategy: NONE

  manyToOne:
    user:
      targetEntity: User
      joinColumn:
        name: user_uuid
        referencedColumnName: uuid
    subject:
      targetEntity: Demands\Domain\Subject
      joinColumn:
        name: subject_uuid
        referencedColumnName: uuid
