Users\Domain\User:
  type: entity
  table: users

  id:
    uuid:
      type: string
      generator:
        strategy: NONE

  fields:
    username:
      type: string
      nullable: false
    roles:
      type: json
      nullable: false
    importedAt:
      type: datetime
      nullable: true
    password:
      type: string
      nullable: false

  oneToMany:
    qualifications:
      targetEntity: Qualification
      mappedBy: user

  manyToOne:
    importedBy:
      targetEntity: User
      joinColumn:
        name: user_uuid
        referencedColumnName: uuid

  oneToOne:
    calendar:
      targetEntity: Calendar
      inversedBy: uuid
      joinColumn:
        name: calendar_uuid
        referencedColumnName: uuid
