User:
  type: entity
  table: users

  id:
    uuid:
      type: string
      generator:
        strategy: AUTO

  fields:
    username:
      type: string
      nullable: false
    roles:
      type: json
      nullable: false
    importedAt:
      type: datetime
      nullable: false
    apiToken:
      type: string
      nullable: true
    password:
      type: string
      nullable: false

  manyToOne:
    qualification:
      targetEntity: Subject
      joinColumn:
        name: qualification_uuid
        referencedColumnName: uuid
    importedBy:
      targetEntity: User
      joinColumn:
        name: user_uuid
        referencedColumnName: uuid

  oneToOne:
    calendar:
      targetEntity: Calendar
      mappedBy: user