version: '3'
services:
  ### FRONTEND ###
  frontend:
    build: docker/frontend
    container_name: frontend
    networks:
      demands:
        ipv4_address: 192.168.16.2
    volumes:
      - ./frontend:/var/www/frontend:Z
    ports:
      - "80:4200"

  ### API ###
  api:
    build: docker/api
    container_name: api
    networks:
      demands:
        ipv4_address: 192.168.16.3
    volumes:
      - ./api:/var/www/api:Z
    ports:
      - "81:8080"

  ### DATABASE ###
  db-service:
    image: postgres:11-alpine
    container_name: database
    networks:
      demands:
        ipv4_address: 192.168.16.4
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
    - "5432:5432"

volumes:
  db-service-data:

networks:
  demands:
    ipam:
      driver: default
      config:
        - subnet: 192.168.16.0/20
