security:
    encoders:
        App\Entity\User: plaintext
#            algorithm: bcrypt

        Symfony\Component\Security\Core\User\User: plaintext
    providers:
        entity_provider:
            entity:
                class: App\Entity\User
                property: username
        in_memory:
            memory:
                users:
                    admin:
                        password: admin
                        roles: 'Admin'
                    dziekan:
                        password: dziekan
                        roles: 'Dziekan'
                    kierownikZakladu:
                        password: kierownikZakladu
                        roles: 'KierownikZakladu'
                    nauczyciel:
                        password: nauczyciel
                        roles: 'Nauczyciel'
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern:  ^/login
            stateless: true
            anonymous: true
            provider: in_memory
            json_login:
                check_path: /login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        register:
            pattern:  ^/register
            stateless: true
            anonymous: true

        api:
            pattern:  ^/
            stateless: true
            anonymous: false
            provider: in_memory
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }