security:
    encoders:
        Users\Domain\User:
#            algorithm: argon2i
            algorithm: bcrypt
            cost: 12
    providers:
        app_user_provider:
            entity:
                class: Users\Domain\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            logout: ~

            guard:
                authenticators:
                    - Common\Security\TokenAuthenticator
    access_control:
