security:
    encoders:
        Users\Domain\User:
#            algorithm: argon2i
            algorithm: bcrypt
            cost: 12
        App\Entity\TEst:
            algorithm: bcrypt

    providers:
        app_user_provider:
            entity:
                class: App\Entity\TEst
                property: username
        # used to reload user from session & other Behat (e.g. switch_user)
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            logout: ~

            guard:
                authenticators:
                    - Common\Security\TokenAuthenticator
    access_control:
