Demands\Domain\Demand:
  type: entity
  table: demands

  id:
    uuid:
      type: string
      generator:
        strategy: NONE

  fields:
    status:
      type: integer
      nullable: false
    schoolYear:
      type: string
      nullable: false
    semester:
      type: string
      nullable: false
    institute:
      type: string
      nullable: false
    department:
      type: string
      nullable: false
    exportedAt:
      type: datetime
      nullable: true
    importedAt:
      type: datetime
      nullable: true

  manyToOne:
    subject:
      targetEntity: Subject
      cascade: ["persist"]
      joinColumn:
        name: subject_uuid
        referencedColumnName: uuid
    group:
      targetEntity: Group
      cascade: ["persist"]
      joinColumn:
        name: group_uuid
        referencedColumnName: uuid
    importedBy:
      targetEntity: Users\Domain\User
      cascade: ["persist"]
      joinColumn:
        name: imported_by_uuid
        referencedColumnName: uuid
    exportedBy:
      targetEntity: Users\Domain\User
      cascade: ["persist"]
      joinColumn:
        name: exported_by_uuid
        referencedColumnName: uuid

  oneToMany:
    lectureSets:
      targetEntity: LectureSet
      mappedBy: demand
      cascade: ["persist"]
      fetch: 'EAGER'
