Demands\Domain\Group:
  type: entity
  table: groups

  id:
    uuid:
      type: string
      generator:
        strategy: NONE

  fields:
    name:
      type: string
      nullable: false
    type:
      type: integer
      nullable: false

  oneToMany:
    demands:
      targetEntity: Demand
      mappedBy: group
