Demands\Domain\LectureSet:
  type: entity
  table: lecture_sets

  id:
    uuid:
      type: string
      generator:
        strategy: NONE

  fields:
    lectureType:
      type: integer
      nullable: false
    notes:
      type: string
      nullable: true
    hoursToDistribute:
      type: integer
      nullable: false
    assignedAt:
      type: datetime
      nullable: true

  manyToOne:
    lecturer:
      targetEntity: Users\Domain\User
      joinColumn:
        name: lecturer_uuid
        referencedColumnName: uuid
    demand:
      targetEntity: Demand
      inversedBy: lectureSets
      joinColumn:
        name: demand_uuid
        referencedColumnName: uuid
    assignedBy:
      targetEntity: Users\Domain\User
      joinColumn:
        name: assigned_by_uuid
        referencedColumnName: uuid

  oneToMany:
    allocatedWeeks:
      targetEntity: Week
      mappedBy: lectureSet
