Demands\Domain\Place:
  type: entity
  table: places
  uniqueConstraints:
    search_idx:
      columns: [ building, room ]

  id:
    uuid:
      type: string
      generator:
        strategy: NONE

  fields:
    building:
      type: integer
      nullable: false
    room:
      type: integer
      nullable: false
