#demands
import_study_plans:
  path: /import-study-plans
  controller: Demands\Infrastructure\Symfony\Controller\DemandController::importStudyPlans
  methods: POST

list_demands:
  path: /demands
  controller: Demands\Infrastructure\Symfony\Controller\DemandController::list
  methods: GET

list_places:
  path: /places
  controller: Demands\Infrastructure\Symfony\Controller\DemandController::listPlaces
  methods: GET

update_demand:
  path: /update/{uuid}
  controller: Demands\Infrastructure\Symfony\Controller\DemandController::updateDemand
  methods: PUT
  defaults: # Exception is parsed to json and can be handled in client side (Angular)
    _format: json

decline_demand:
  path: /decline/{uuid}
  controller: Demands\Infrastructure\Symfony\Controller\DemandController::declineDemand
  methods: PUT

accept_demand:
  path: /accept/{uuid}
  controller: Demands\Infrastructure\Symfony\Controller\DemandController::acceptDemand
  methods: PUT

get_details:
  path: /details/{uuid}
  controller: Demands\Infrastructure\Symfony\Controller\DemandController::getDetails
  methods: GET

export_demands:
  path: /export-demands
  controller: Demands\Infrastructure\Symfony\Controller\DemandController::exportDemands
  methods: PUT

download_demand:
  path: /download-demand/{uuid}
  controller: Demands\Infrastructure\Symfony\Controller\DemandController::downloadDemand
  methods: GET

assign_demand:
  path: /assign-demand
  controller: Demands\Infrastructure\Symfony\Controller\DemandController::assignDemand
  methods: PUT

#users

login_check:
  path: /login_check

update_profile:
  path: /update-profile
  controller: Users\Infrastructure\Symfony\Controller\UserController::updateProfile
  methods: PUT

profile-details:
  path: /profile-details
  controller: Users\Infrastructure\Symfony\Controller\UserController::getProfile
  methods: GET

get_qualified_lecturers:
  path: /lecturers/{subjectName}
  controller: Users\Infrastructure\Symfony\Controller\UserController::getQualifiedLecturers
  methods: GET

import_lecturers:
  path: /import-lecturers
  controller: Users\Infrastructure\Symfony\Controller\UserController::importLecturers
  methods: POST

lecturers:
  path: /lecturers
  controller: Users\Infrastructure\Symfony\Controller\UserController::lecturers
  methods: GET
