# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'pl'

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    #fixtures
    App\DataFixtures\:
        resource: '../src/DataFixtures'

#DEMANDS

    #Controllers
    Demands\Infrastructure\Symfony\Controller\DemandController:
        tags:
            - { name: controller.service_arguments, typehints: true }

    #Repositories
    Demands\Infrastructure\Doctrine\Repository\:
        resource: '../src/Demands/Infrastructure/Doctrine/Repository'

    #RepositoryInterfaces
    Demands\Domain\Repository\DemandRepository: '@Demands\Infrastructure\Doctrine\Repository\DoctrineDemandRepository'
    Demands\Domain\Repository\SubjectRepository: '@Demands\Infrastructure\Doctrine\Repository\DoctrineSubjectRepository'
    Demands\Domain\Repository\GroupRepository: '@Demands\Infrastructure\Doctrine\Repository\DoctrineGroupRepository'
    Demands\Domain\Repository\PlaceRepository: '@Demands\Infrastructure\Doctrine\Repository\DoctrinePlaceRepository'

    #Handlers
    Demands\Application\Handler\AcceptDemandHandler:
        tags:
            - { name: tactician.handler, typehints: true }

    Demands\Application\Handler\AssignDemandHandler:
        tags:
            - { name: tactician.handler, typehints: true }

    Demands\Application\Handler\DeclineDemandHandler:
        tags:
            - { name: tactician.handler, typehints: true }

    Demands\Application\Handler\DownloadDemandHandler:
        tags:
            - { name: tactician.handler, typehints: true }

    Demands\Application\Handler\ExportDemandsHandler:
        tags:
            - { name: tactician.handler, typehints: true }

    Demands\Application\Handler\ImportStudyPlansHandler:
        tags:
            - { name: tactician.handler, typehints: true }

    Demands\Application\Handler\UpdateDemandHandler:
        tags:
            - { name: tactician.handler, typehints: true }

    #miscellaneous
    Demands\Domain\StatusResolver:
    Demands\Domain\FileMaker:
    Demands\Application\Service\DemandService:

#USERS

    #Controllers
    Users\Infrastructure\Symfony\Controller\UserController:
        tags:
            - { name: controller.service_arguments, typehints: true }

    #Repositories
    Users\Infrastructure\Doctrine\Repository\:
        resource: '../src/Users/Infrastructure/Doctrine/Repository'


    #RepositoryInterfaces
    Users\Domain\Repository\UserRepository: '@Users\Infrastructure\Doctrine\Repository\DoctrineUserRepository'

    #Handlers
    Users\Application\Handler\ImportUsersHandler:
        tags:
            - { name: tactician.handler, typehints: true }


    #Common
    Common\Http\:
        resource: '../src/Common/Http'

    Users\Application\Service\UserService:
