# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'pl'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Demands\:
        resource: '../src/Demands/*'
        exclude: '../src/Demands/Infrastructure/{InMemory}'
    Users\:
        resource: '../src/Users/*'
        exclude: '../src/Users/Infrastructure/{InMemory}'
    Common\:
        resource: '../src/Common/*'
#        exclude: '../src/Common/Infrastructure/{InMemory}'

    #Repositories
    Users\Infrastructure\Doctrine\Repository\DoctrineUserRepository:

    #Handlers
    Demands\Application\Handler\AcceptDemandHandler:
        tags:
            - { name: tactician.handler, typehints: true }

    Demands\Application\Handler\AssignDemandHandler:
        tags:
            - { name: tactician.handler, typehints: true }

    Demands\Application\Handler\DeclineDemandHandler:
        tags:
            - { name: tactician.handler, typehints: true }

    Demands\Application\Handler\DownloadDemandHandler:
        tags:
            - { name: tactician.handler, typehints: true }

    Demands\Application\Handler\ExportDemandsHandler:
        tags:
            - { name: tactician.handler, typehints: true }

    Demands\Application\Handler\ImportStudyPlansHandler:
        tags:
            - { name: tactician.handler, typehints: true }

    Demands\Application\Handler\UpdateDemandHandler:
        tags:
            - { name: tactician.handler, typehints: true }



    Users\Application\Handler\ImportUsersHandler:
        tags:
            - { name: tactician.handler, typehints: true }